### ISSUE TITLE
Write Payment interface, implement CashPayment, CheckPayment, CreditPayment classes

### ISSUE THREAD

**Issue by Ademan** [Ademan/Post#13]

**Comment by Ademan** [comment]
Because the Payment classes require the amountDue when they're constructed, this creates some trouble in the TransactionReader class.

I also am not sure amountDue should be property of a payment in the first place. A payment may have an amount tendered (which we read from the text file for CASH and CHECK transactions), but amountDue is an intrinsic property of a transaction, not the payment itself.

**Comment by lmillik** [comment]
In the sample UML in the reader, the Payment classes have an amountDue field. We could just move the initialization of the amountDue out of the contructor.

**Comment by Ademan** [comment]
Hrm, well if that's what he wants. I'll add a setter and a default
constructor so I can set it later, and I'll bundle that with the required
fix to TransactionReader. Thanks

**Comment by lmillik** [comment]
Also, keep in mind that the transactions.txt file is a simulation of a bunch of command line inputs. The items are added to the transaction one at a time, not in bulk, and the payment should only happen after all the items have been added so that the amountDue is known. This is how it has to work for the GUI version, so we should make sure that it works for this version.

**Comment by ironsquishy** [comment]
You guys can check out group A's repo. Anthony said they are done with the project when it comes to code.

**Comment by Ademan** [comment]
I think this issue is done?
